stages:
  - build

build:
  stage: build
  image: sacurio/debianpackager:0.2
  before_script:
    - 'apt-get update && apt-get install -y --no-install-recommends golang-github-onsi-ginkgo-dev golang-gomega-dev golang-x-text-dev'
    - "eval $(ssh-agent -s)"
    - 'ssh-add <(echo "$DEBIAN_PACKAGING_PRIVATE_KEY")'
    - mkdir -p ~/.ssh; chmod 700 ~/.ssh
  script:
    - gbp buildpackage --git-ignore-branch
    - mkdir debian_build
    - 'cp ../*.{deb,dsc,changes,tar.xz} debian_build'
    - 'scp -v debian_build/*.deb repo@debian.autonomia.digital:/home/repo/packages/upload'
  artifacts:
    paths:
      - 'debian_build/*.deb'
      - 'debian_build/*.dsc'
      - 'debian_build/*.changes'
      - 'debian_build/*.tar.xz'
